#!/bin/bash

pwgen () {
    openssl rand -base64 12
}

[ -f .pass ] || {
    cat <<EOF > .pass
export POSTGRES_PASS=$(pwgen)
export POSTGRES_PASS_GRAFANA=$(pwgen)
export POSTGRES_PASS_SYSMON=$(pwgen)
EOF
}

. .pass

if type docker-compose 2> /dev/null; then
    docker-compose $@
else
    docker compose $@
fi
