{
 "title": "Erlang applications top",
 "tags": [
  "erlang",
  "top"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Postgres", "label": "datasource", "query": "postgres" },
   {
    "name": "node",
    "query": "SELECT DISTINCT node FROM node ORDER BY node ASC;"
   }
  ]
 },
 "panels": [
  {
   "title": "reductions per application (log scale)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH tp(tp) AS (VALUES(($__unixEpochTo()-$__unixEpochFrom())/100))\nSELECT\n  (extract(epoch from ts)/tp)::bigint*tp AS time,\n  application AS \"metric\",\n  log(avg(value))\nFROM\n  app_top, tp\nWHERE\n  unit = 'reductions' AND\n  node = '[[node]]' AND\n  ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY application,time\nORDER BY time"
    }
   ]
  },
  {
   "title": "memory per application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "WITH tp(tp) AS (VALUES(($__unixEpochTo()-$__unixEpochFrom())/100))\nSELECT\n  (extract(epoch from ts)/tp)::bigint*tp AS time,\n  application AS \"metric\",\n  avg(value)\nFROM\n  app_top, tp\nWHERE\n  unit = 'memory' AND\n  node = '[[node]]' AND\n  ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY application,time\nORDER BY time"
    }
   ]
  },
  {
   "title": "processes per application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH tp(tp) AS (VALUES(($__unixEpochTo()-$__unixEpochFrom())/100))\nSELECT\n  (extract(epoch from ts)/tp)::bigint*tp AS time,\n  application AS \"metric\",\n  avg(value)\nFROM\n  app_top, tp\nWHERE\n  unit = 'processes' AND\n  node = '[[node]]' AND\n  ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY application,time\nORDER BY time"
    }
   ]
  },
  {
   "title": "% of processes execuing function",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH tp(tp) AS (VALUES(($__unixEpochTo()-$__unixEpochFrom())/100))\nSELECT\n  (extract(epoch from ts)/tp)::bigint*tp AS time,\n  fun AS \"metric\",\n  avg(num_processes)\nFROM\n  fun_top, tp\nWHERE\n  fun_type = 'current_function' AND\n  node = '[[node]]' AND\n  ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY fun,time\nORDER BY time"
    }
   ]
  },
  {
   "title": "% of processes started from this function",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH tp(tp) AS (VALUES(($__unixEpochTo()-$__unixEpochFrom())/100))\nSELECT\n  (extract(epoch from ts)/tp)::bigint*tp AS time,\n  fun AS \"metric\",\n  avg(num_processes)\nFROM\n  fun_top, tp\nWHERE\n  fun_type = 'initial_call' AND\n  node = '[[node]]' AND\n  ts BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY fun,time\nORDER BY time"
    }
   ]
  }
 ]
}