{
 "title": "Beamformer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   { "name": "Node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "emqx_ds_subs", "legendFormat": "{{db}}-{{shard}}" }
   ]
  },
  {
   "title": "Stuck/unstuck subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(emqx_ds_subs_stuck_total[$__rate_interval])",
     "legendFormat": "stuck-{{db}}"
    },
    {
     "expr": "rate(emqx_ds_subs_unstuck_total[$__rate_interval])",
     "legendFormat": "unstuck-{{db}}"
    }
   ]
  },
  {
   "title": "RT beams/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(emqx_ds_subs_beams_sent_total{type=\"rt\"}[$__rate_interval])",
     "legendFormat": "{{db}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Catchup Beams/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(emqx_ds_subs_beams_sent_total{type=\"catchup\"}[$__rate_interval])",
     "legendFormat": "{{db}}-{{type}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Realtime Fulfill time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "emqx_ds_subs_fulfill_time{interval=\"current\", type=\"rt\"}",
     "legendFormat": "{{db}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Catchup fulfill time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "emqx_ds_subs_fulfill_time{interval=\"current\", type=\"catchup\"}",
     "legendFormat": "{{db}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Realtime Request sharing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "emqx_ds_subs_request_sharing{interval=\"current\", type=\"rt\"}",
     "legendFormat": "{{db}}-{{type}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Catchup Request sharing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "emqx_ds_subs_request_sharing{interval=\"current\", type=\"catchup\"}",
     "legendFormat": "{{db}}-{{type}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Fanout time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "emqx_ds_subs_fanout_time{interval=\"current\"}",
     "legendFormat": "{{db}}-{{shard}}"
    }
   ]
  }
 ]
}