{
 "title": "Durable storage",
 "time": { "from": "2025-09-01T16:19:28.175Z", "to": "2025-09-01T16:37:59.696Z" },
 "templating": {
  "list": [
   { "name": "db", "query": { "query": "label_values(db)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Catch-up subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "emqx_ds_subs{db=\"$db\", type=\"catchup\"}",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Realtime subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "emqx_ds_subs{db=\"$db\", type=\"rt\"}",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Buffer flush time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "emqx_ds_buffer_flush_time{db=\"$db\", interval=\"current\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Write-induced latency",
   "type": "timeseries",
   "description": "Contribution to end-to-end latency that comes from the write buffer.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "emqx_ds_buffer_latency{db=\"$db\", interval=\"current\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Batches/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(emqx_ds_buffer_batches{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Transactions/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(emqx_ds_buffer_messages{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Total data written (decimal)",
   "type": "timeseries",
   "description": "Total volume of data written to the database that includes all shards.\nThis is a lower estimate that doesn't include message metadata.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(emqx_ds_buffer_bytes{db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Beamformers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stuck/unstuck stream subscriptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "rate(emqx_ds_subs_stuck_total{db=\"$db\"}[$__rate_interval])",
       "legendFormat": "stuck-{{db}}"
      },
      {
       "expr": "rate(emqx_ds_subs_unstuck_total{db=\"$db\"}[$__rate_interval])",
       "legendFormat": "unstuck-{{db}}"
      }
     ]
    },
    {
     "title": "Fanout time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "emqx_ds_subs_fanout_time{interval=\"current\", db=\"$db\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request sharing (realtime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "emqx_ds_subs_request_sharing{interval=\"current\", type=\"rt\", db=\"$db\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Request sharing (catchup)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "emqx_ds_subs_request_sharing{interval=\"current\", type=\"catchup\", db=\"$db\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Fulfill time (realtime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "emqx_ds_subs_fulfill_time{interval=\"current\", type=\"rt\", db=\"$db\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Fulfill time (catchup)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "emqx_ds_subs_fulfill_time{interval=\"current\", type=\"catchup\", db=\"$db\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Beams/s (realtime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(emqx_ds_subs_beams_sent_total{type=\"rt\", db=\"$db\"}[$__rate_interval])",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Beams/s (realtime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(emqx_ds_subs_beams_sent_total{type=\"catchup\", db=\"$db\"}[$__rate_interval])",
       "legendFormat": "{{shard}}"
      }
     ]
    }
   ]
  }
 ]
}