{
 "title": "Durable storage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "db", "query": { "query": "emqx_ds_" } }
  ]
 },
 "panels": [
  {
   "title": "Replay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "next time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "emqx_ds_builtin_next_time{}" }
   ]
  },
  {
   "title": "LTS iteration metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(emqx_ds_storage_bitfield_lts_counter_next{}[$__rate_interval])"
    },
    {
     "expr": "rate(emqx_ds_storage_bitfield_lts_counter_seek{}[$__rate_interval])"
    }
   ]
  },
  { "title": "Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Egress flush time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "emqx_ds_egress_flush_time" }
   ]
  },
  {
   "title": "Egress n batches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(emqx_ds_egress_batches{}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Avg batch messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "rate(emqx_ds_egress_messages{}[$__rate_interval]) / rate(emqx_ds_egress_batches{}[$__rate_interval])"
    }
   ]
  }
 ]
}