{
 "title": "Durable storage",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "db", "query": { "query": "label_values(db)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Poll queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(emqx_ds_poll_pendingq_len{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Waiting queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(emqx_ds_poll_waitq_len{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  { "title": "Polls requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Submitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(emqx_ds_poll_requests{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Fulfilled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(emqx_ds_poll_requests_fulfilled{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Expired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(emqx_ds_poll_requests_expired{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(emqx_ds_poll_requests_dropped{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Sharing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(emqx_ds_poll_request_sharing{db=\"$db\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{db}}/{{shard}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buffer flush time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "emqx_ds_buffer_flush_time{db=\"$db\"}",
       "legendFormat": "{{instance}}/{{db}}/{{shard}}"
      }
     ]
    },
    {
     "title": "Write-induced latency",
     "type": "timeseries",
     "description": "Contribution to end-to-end latency that comes from the write buffer.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "emqx_ds_buffer_latency{db=\"$db\"}",
       "legendFormat": "{{instance}}/{{db}}/{{shard}}"
      }
     ]
    },
    {
     "title": "Batches/s",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "rate(emqx_ds_buffer_batches{db=\"$db\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{db}}/{{shard}}"
      }
     ]
    },
    {
     "title": "Messages/s",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "rate(emqx_ds_buffer_messages{db=\"$db\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{db}}/{{shard}}"
      }
     ]
    },
    {
     "title": "Bytes/s (total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(emqx_ds_buffer_bytes{db=\"$db\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}