{
 "title": "emqttb",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of workers per group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "emqttb_group_n_workers{}", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Client spawn rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(emqttb_group_n_workers{}[30s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Published messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(emqttb_published_messages{}[30s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Received messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(emqttb_received_messages{}[30s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Autorate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "emqttb_autorate_rate", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "End-to-end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "emqttb_e2e_latency", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Number of pending operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "emqttb_group_n_pending", "legendFormat": "{{group}}/{{operation}}" }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "emqttb_group_op_time", "legendFormat": "{{group}}/{{operation}}" }
   ]
  },
  {
   "title": "Persistent session throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "emqttb_pers_sess_pub_throughput_sum{}"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "emqttb_group_op_time", "legendFormat": "{{group}}/{{operation}}" }
   ]
  },
  {
   "title": "Number of gaps and repeats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "emqttb_gaps_number", "legendFormat": "Gap: {{group}}" },
    { "expr": "emqttb_repeats_number", "legendFormat": "Repeat: {{group}}" }
   ]
  },
  {
   "title": "Size of gaps and repeats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "emqttb_gap_size", "legendFormat": "Gap: {{group}}" },
    { "expr": "emqttb_repeat_size", "legendFormat": "Repeat: {{group}}" }
   ]
  },
  {
   "title": "Number of sequences",
   "type": "timeseries",
   "description": "Count the number of triples sender client id, receiver client id, and topic. \nverify-sequence must be enabled.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "emqttb_n_sequences", "legendFormat": "{{group}}" }
   ]
  }
 ]
}