{
 "title": "EMQX monitoring",
 "description": "Clone of https://github.com/emqx/emqx/blob/master/apps/emqx_prometheus/grafana_template/EMQ.json",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(emqx_connections_count, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_connections_count{instance=~\"$host\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_connections_max{instance=~\"$host\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Session",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_sessions_count{instance=~\"$host\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_sessions_max{instance=~\"$host\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Subscribers & Suboptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_suboptions_count{instance=~\"$host\"}",
     "legendFormat": "Subopt-Current"
    },
    {
     "expr": "emqx_suboptions_max{instance=~\"$host\"}",
     "legendFormat": "Subopt-Max"
    },
    {
     "expr": "emqx_subscribers_count{instance=~\"$host\"}",
     "legendFormat": "Suber-Current"
    },
    {
     "expr": "emqx_subscribers_max{instance=~\"$host\"}",
     "legendFormat": "Suber-Max"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_subscriptions_count{instance=~\"$host\"}",
     "legendFormat": "Normal-Current"
    },
    {
     "expr": "emqx_subscriptions_max{instance=~\"$host\"}",
     "legendFormat": "Normal-Max"
    },
    {
     "expr": "emqx_subscriptions_shared_count{instance=~\"$host\"}",
     "legendFormat": "Shared-Current"
    },
    {
     "expr": "emqx_subscriptions_shared_max{instance=~\"$host\"}",
     "legendFormat": "Shared-Max"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_routes_count{instance=~\"$host\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_routes_max{instance=~\"$host\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Retained Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "emqx_retained_count{instance=~\"$host\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_retained_max{instance=~\"$host\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Messages Overview",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_received{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(emqx_messages_sent{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_sent{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(emqx_messages_retained{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_retained{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Retained"
    },
    {
     "expr": "sum(rate(emqx_messages_dropped{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_dropped{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum(rate(emqx_messages_delayed{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_delayed{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Delayed"
    },
    {
     "expr": "sum(rate(emqx_messages_forward{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_forward{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Forward"
    }
   ]
  },
  {
   "title": "Messages/Delivery Dropped",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_dropped{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_dropped{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Message.Dropped"
    },
    {
     "expr": "sum(rate(emqx_messages_dropped_expired {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_dropped_expired {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Message.Dropped.Expired"
    },
    {
     "expr": "sum(rate(emqx_messages_dropped_no_subscribers {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_dropped_no_subscribers {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Message.Dropped.no_subscribers"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped {instance=~\"$host\"}[$__interval]) or irate(emqx_delivery_dropped {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Delivery.Dropped"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_no_local{instance=~\"$host\"}[$__interval]) or irate(emqx_delivery_dropped_no_local {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Delivery.Dropped.no_local"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_too_large {instance=~\"$host\"}[$__interval]) or irate(emqx_delivery_dropped_too_large {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Delivery.Dropped.too_large"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_qos0_msg {instance=~\"$host\"}[$__interval]) or irate(emqx_delivery_dropped_qos0_msg {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Delivery.Dropped.qos0_msg"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_queue_full {instance=~\"$host\"}[$__interval]) or irate(emqx_delivery_dropped_queue_full {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Delivery.Dropped.queue_full"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_expired {instance=~\"$host\"}[$__interval]) or irate(emqx_delivery_dropped_expired {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Delivery.Dropped.expired"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_received{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(emqx_messages_qos0_received {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_qos0_received {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Received.QoS0"
    },
    {
     "expr": "sum(rate(emqx_messages_qos1_received {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_qos1_received {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Received.QoS1"
    },
    {
     "expr": "sum(rate(emqx_messages_qos2_received {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_qos2_received {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Received.QoS2"
    }
   ]
  },
  {
   "title": "Messages  Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_sent{instance=~\"$host\"}[$__interval]) or irate(emqx_messages_sent{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(emqx_messages_qos0_sent {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_qos0_sent {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Sent.QoS0"
    },
    {
     "expr": "sum(rate(emqx_messages_qos1_sent {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_qos1_sent {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Sent.QoS1"
    },
    {
     "expr": "sum(rate(emqx_messages_qos2_sent {instance=~\"$host\"}[$__interval]) or irate(emqx_messages_qos2_sent {instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Sent.QoS2"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_bytes_received{instance=~\"$host\"}[$__interval]) or irate(emqx_bytes_received{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(rate(emqx_bytes_sent{instance=~\"$host\"}[$__interval]) or irate(emqx_bytes_sent{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Packets connect",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(emqx_packets_connect{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Connect"
    },
    {
     "expr": "rate(emqx_packets_connack_sent{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Connack sent"
    },
    {
     "expr": "rate(emqx_packets_disconnect_sent{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Disconnect sent"
    },
    {
     "expr": "rate(emqx_packets_connack_error {instance=~\"$host\"}[$__interval])",
     "legendFormat": "connack_error"
    },
    {
     "expr": "rate(emqx_packets_connack_auth_error {instance=~\"$host\"}[$__interval])",
     "legendFormat": "connack_auth_error"
    },
    {
     "expr": "rate(emqx_packets_auth_received {instance=~\"$host\"}[$__interval])",
     "legendFormat": "Auth"
    },
    {
     "expr": "rate(emqx_packets_auth_sent {instance=~\"$host\"}[$__interval])",
     "legendFormat": "Auth sent"
    }
   ]
  },
  {
   "title": "Packets subscribe/unsubscribe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(emqx_packets_subscribe_received{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Subscribe received"
    },
    {
     "expr": "rate(emqx_packets_suback_sent{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Suback sent"
    },
    {
     "expr": "rate(emqx_packets_unsubscribe_received{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Unsubscribe received"
    },
    {
     "expr": "rate(emqx_packets_unsuback_sent{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Unsuback sent"
    },
    {
     "expr": "rate(emqx_packets_subscribe_auth_error {instance=~\"$host\"}[$__interval])",
     "legendFormat": "sub_auth_error"
    },
    {
     "expr": "rate(emqx_packets_subscribe_error {instance=~\"$host\"}[$__interval])",
     "legendFormat": "sub_error"
    },
    {
     "expr": "rate(emqx_packets_unsubscribe_error {instance=~\"$host\"}[$__interval])",
     "legendFormat": "unsub_error"
    }
   ]
  },
  {
   "title": "Packets ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_pingreq_received{instance=~\"$host\"}[$__interval]) or irate(emqx_packets_pingreq_received{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Pingreq sent"
    },
    {
     "expr": "sum(rate(emqx_packets_pingresp_sent{instance=~\"$host\"}[$__interval]) or irate(emqx_packets_pingresp_sent{instance=~\"$host\"}[$__interval]))",
     "legendFormat": "Pingresp sent"
    }
   ]
  },
  {
   "title": "Packets publish",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(emqx_packets_publish_received{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Publish received"
    },
    {
     "expr": "rate(emqx_packets_publish_sent{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Publish sent"
    },
    {
     "expr": "rate(emqx_packets_puback_received{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Puback received"
    },
    {
     "expr": "rate(emqx_packets_puback_sent{instance=~\"$host\"}[$__interval])",
     "legendFormat": "Puback sent"
    },
    {
     "expr": "rate(emqx_packets_pubrel_received{instance=~\"$host\"}[$interval])",
     "legendFormat": "Pubrel received"
    },
    {
     "expr": "rate(emqx_packets_pubrel_sent{instance=~\"$host\"}[$interval])",
     "legendFormat": "Pubrel sent"
    },
    {
     "expr": "rate(emqx_packets_pubcomp_received{instance=~\"$host\"}[$interval])",
     "legendFormat": "Pubcomp received"
    },
    {
     "expr": "rate(emqx_packets_pubcomp_sent{instance=~\"$host\"}[$interval])",
     "legendFormat": "Pubcomp sent"
    }
   ]
  }
 ]
}