{
 "title": "Erlang distribution",
 "time": { "from": "2022-02-18T18:18:23.209Z", "to": "2022-02-18T18:25:28.464Z" },
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(emqx_connections_count, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "dist_proc message queue len",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "erlang_vm_dist_proc_message_queue_len{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "dist recv cnt [10 minutes]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(erlang_vm_dist_recv_cnt{instance=\"$node\"}[10m])"
    }
   ]
  },
  {
   "title": "dist send cnt [10 minutes]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(erlang_vm_dist_send_cnt{instance=\"$node\"}[10m])"
    }
   ]
  },
  {
   "title": "dist recv bytes [10 minutes]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(erlang_vm_dist_recv_bytes{instance=\"$node\"}[10m])"
    }
   ]
  },
  {
   "title": "dist send bytes [10 minutes]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(erlang_vm_dist_send_bytes{instance=\"$node\"}[10m]) "
    }
   ]
  }
 ]
}