{
 "title": "emqx mria",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
    }
   },
   { "name": "DS__VICTORIAMETRICS", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "emqx_host",
    "label": "emqx_host",
    "query": {
     "query": "label_values(emqx_connections_count, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Replicant metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "emqx_mria_lag{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  {
   "title": "replayq len",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "emqx_mria_replayq_len{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  {
   "title": "bootstrap time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "emqx_mria_bootstrap_time{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  {
   "title": "replicant mql",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "emqx_mria_message_queue_len{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  {
   "title": "bootstrap num keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "emqx_mria_bootstrap_num_keys{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  { "title": "Core metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "last intercepted trans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "emqx_mria_last_intercepted_trans{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  {
   "title": "server mql",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "emqx_mria_server_mql{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  {
   "title": "weight",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emqx_mria_weight{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  {
   "title": "replicants",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emqx_mria_replicants{instance=~'$emqx_host'}",
     "legendFormat": "{{shard}} - {{instance}}"
    }
   ]
  },
  { "title": "Misc mnesia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "mnesia stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(erlang_mnesia_committed_transactions{instance=~'$emqx_host'}[1m])",
     "legendFormat": "committed - {{instance}}"
    },
    {
     "expr": "rate(erlang_mnesia_failed_transactions{instance=~'$emqx_host'}[1m])",
     "legendFormat": "failed - {{instance}}"
    },
    {
     "expr": "erlang_mnesia_held_locks{instance=~'$emqx_host'}",
     "legendFormat": "held locks - {{instance}}"
    },
    {
     "expr": "erlang_mnesia_lock_queue{instance=~'$emqx_host'}",
     "legendFormat": "lock queue - {{instance}}"
    }
   ]
  },
  {
   "title": "mnesia tables - size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "erlang_mnesia_tablewise_size{instance=~'$emqx_host'}",
     "legendFormat": "{{table}} - {{instance}}"
    }
   ]
  },
  {
   "title": "mnesia tables - memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "erlang_mnesia_tablewise_memory_usage_bytes{instance=~'$emqx_host'}",
     "legendFormat": "memory - {{table}} - {{instance}}"
    }
   ]
  }
 ]
}