{
 "title": "Process history",
 "time": { "from": "2020-07-31T09:51:33.904Z", "to": "2020-07-31T10:06:31.905Z" },
 "templating": {
  "list": [
   { "name": "Postgres", "label": "datasource", "query": "postgres" },
   {
    "name": "node",
    "query": "SELECT DISTINCT node FROM node ORDER BY node ASC;"
   },
   { "name": "regname", "label": "Registered name" },
   { "name": "pid" }
  ]
 },
 "panels": [
  {
   "title": "Reductions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  dreductions\nFROM\n  prc\nWHERE\n  (ts BETWEEN $__timeFrom() AND $__timeTo()) AND node='[[node]]' AND (('[[pid]]' <> '' AND pid='[[pid]]') OR ('[[regname]]' <> '' AND registered_name='[[regname]]'))\nORDER BY ts\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  stack_size, heap_size, total_heap_size, memory\nFROM\n  prc\nWHERE\n  (ts BETWEEN $__timeFrom() AND $__timeTo()) AND node='[[node]]' AND (pid='[[pid]]' OR registered_name='[[regname]]')\nORDER BY ts\n"
    }
   ]
  },
  {
   "title": "Message queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts), message_queue_len\nFROM prc\nWHERE  (ts BETWEEN $__timeFrom() AND $__timeTo()) AND node='[[node]]' AND (('[[pid]]' <> '' AND pid='[[pid]]') OR ('[[regname]]' <> '' AND registered_name='[[regname]]'))\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Current function",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ts, current_function, current_stacktrace FROM prc \nWHERE (ts BETWEEN $__timeFrom() AND $__timeTo())\n AND node='[[node]]' AND (('[[pid]]' <> '' AND pid='[[pid]]') OR ('[[regname]]' <> '' AND registered_name='[[regname]]'))\n AND current_function NOT SIMILAR TO 'gen_server:loop/%'\nAND current_function NOT SIMILAR TO 'gen_statem:loop_receive/%'\n"
    }
   ]
  }
 ]
}