apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: "$POSTGRES_URL"
    database: "system_monitor"
    user: "grafana"
    secureJsonData:
      password: "$POSTGRES_PASS_GRAFANA"
    jsonData:
      sslmode: "$POSTGRES_SSL_MODE"
      timescaledb: false

  - name: Prometheus
    type: prometheus
    url: "$PROMETHEUS_URL"
    access: "proxy"
    basicAuth: false
